version: 2

jobs:
  greetings:
    machine: true
    environment:
      FOO: BAR
    steps:
      - run:
          name: Greeting
          command: |
            echo Hello, world.
            echo Foo: $FOO
  date:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Print the Current Time
          command: date

  repo_size:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Echo repo size
          command: du -sh

workflows:
  version: 2
  run_date:
    jobs:
      - greetings:
          type: approval
      - date:
          requires:
            - greetings
  run_repo_size:
    jobs:
      - greetings:
          type: approval
      - repo_size:
          requires:
            - greetings
  run_all_jobs:
    jobs:
      - greetings:
          type: approval
      - date:
          requires:
            - greetings
      - repo_size:
          requires:
            - greetings
