version: 2

jobs:
  job1:
    machine: true
    environment:
      FOO: BAR
    steps:
      - checkout
      - run:
          name: Output
          command: |
            echo "This is output prom job1"
  build:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date

workflows:
  version: 2
  run_job1:
    jobs:
      - job1
  run_build:
    jobs:
      - build
